name: CI

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install Dependencies
        run: npm install
      - name: Download and Cache Chromedriver
        uses: browser-actions/cache@v2  
        with:
          browser: chrome
      - name: Build
        run: npm run compile
      - name: Run Tests
        uses: coactions/setup-xvfb@v1
        if: matrix.os != 'ubuntu-latest'
        with:
          run: npm test
          options: "-screen 0 1600x1200x24"
      - name: Run Tests
        uses: coactions/setup-xvfb@v1
        if: matrix.os == 'ubuntu-latest'
        with:
          run: ./node_modules/.bin/run-s test:lint test:unit 
