name: CI

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install Dependencies
        run: npm install
      - name: Download and Install Chromedriver
        run: |
          # Install curl (if not already installed)
          sudo apt-get update
          sudo apt-get install -y curl 

          # Get the latest stable Chromedriver version
          LATEST_CHROMEDRIVER_VERSION=$(curl -sS https://chromedriver.storage.googleapis.com/LATEST_RELEASE)

          # Replace {your-chrome-version} with your actual Chrome major version (e.g., 114)
          CHROMEDRIVER_VERSION=${LATEST_CHROMEDRIVER_VERSION} 

          # Download the correct Chromedriver for your OS (adjust for macOS/Windows)
          wget https://chromedriver.storage.googleapis.com/${CHROMEDRIVER_VERSION}/chromedriver_linux64.zip -O chromedriver.zip
          unzip chromedriver.zip
          chmod +x chromedriver

          # Add Chromedriver to PATH
          sudo mv chromedriver /usr/local/bin/
      - name: Build
        run: npm run compile
      - name: Run Tests
        uses: coactions/setup-xvfb@v1
        if: matrix.os != 'ubuntu-latest'
        with:
          run: npm test
          options: "-screen 0 1600x1200x24"
      - name: Run Tests
        uses: coactions/setup-xvfb@v1
        if: matrix.os == 'ubuntu-latest'
        with:
          run: ./node_modules/.bin/run-s test:lint test:unit 
